import { WondersoftRawRecord } from '../types';

export const SAMPLE_WONDERSOFT_RECORDS: WondersoftRawRecord[] = [
  {
    storeName: 'Karur Main',
    productGroup: 'MEN',
    department: 'Top Wear',
    classBrand: 'GM Fashion',
    colour: 'Navy Blue',
    size: 'M',
    garmentFabric: '100% Cotton',
    ean: '6012345678901',
    mrp: 1299,
    stock: 15,
    styleNo: 'GMSH-01',
    toonLabel: 'TN-SHIRT-NAVY',
    productName: 'Men Slim Fit Cotton Shirt',
    rawRow: {},
  },
  {
    storeName: 'Erode Branch',
    productGroup: 'MEN',
    department: 'Top Wear',
    classBrand: 'GM Fashion',
    colour: 'Navy Blue',
    size: 'M',
    garmentFabric: '100% Cotton',
    ean: '6012345678901',
    mrp: 1299,
    stock: 8,
    styleNo: 'GMSH-01',
    toonLabel: 'TN-SHIRT-NAVY',
    productName: 'Men Slim Fit Cotton Shirt',
    rawRow: {},
  },
  {
    storeName: 'Salem Outlet',
    productGroup: 'MEN',
    department: 'Top Wear',
    classBrand: 'GM Fashion',
    colour: 'Navy Blue',
    size: 'M',
    garmentFabric: '100% Cotton',
    ean: '6012345678901',
    mrp: 1299,
    stock: 12,
    styleNo: 'GMSH-01',
    toonLabel: 'TN-SHIRT-NAVY',
    productName: 'Men Slim Fit Cotton Shirt',
    rawRow: {},
  },
  {
    storeName: 'Karur Main',
    productGroup: 'MEN',
    department: 'Top Wear',
    classBrand: 'GM Fashion',
    colour: 'White',
    size: 'L',
    garmentFabric: '100% Cotton',
    ean: '6012345678902',
    mrp: 1299,
    stock: 10,
    styleNo: 'GMSH-01',
    toonLabel: 'TN-SHIRT-WHT',
    productName: 'Men Slim Fit Cotton Shirt',
    rawRow: {},
  },
  {
    storeName: 'Tirupur Branch',
    productGroup: 'MEN',
    department: 'Top Wear',
    classBrand: 'GM Fashion',
    colour: 'White',
    size: 'L',
    garmentFabric: '100% Cotton',
    ean: '6012345678902',
    mrp: 1299,
    stock: 14,
    styleNo: 'GMSH-01',
    toonLabel: 'TN-SHIRT-WHT',
    productName: 'Men Slim Fit Cotton Shirt',
    rawRow: {},
  },
  {
    storeName: 'Karur Main',
    productGroup: 'MEN',
    department: 'Top Wear',
    classBrand: 'GM Fashion',
    colour: 'Black',
    size: 'XL',
    garmentFabric: 'Polyester Blend',
    ean: '6098765432109',
    mrp: 899,
    stock: 25,
    styleNo: 'GMT-02',
    toonLabel: 'TN-POLO-BLK',
    productName: 'Men Round Neck Polo T-Shirt',
    rawRow: {},
  },
  {
    storeName: 'Coimbatore Central',
    productGroup: 'MEN',
    department: 'Top Wear',
    classBrand: 'GM Fashion',
    colour: 'Black',
    size: 'XL',
    garmentFabric: 'Polyester Blend',
    ean: '6098765432109',
    mrp: 899,
    stock: 18,
    styleNo: 'GMT-02',
    toonLabel: 'TN-POLO-BLK',
    productName: 'Men Round Neck Polo T-Shirt',
    rawRow: {},
  },
  {
    storeName: 'Karur Main',
    productGroup: 'MEN',
    department: 'Bottom Wear',
    classBrand: 'Denim Co',
    colour: 'Dark Blue',
    size: '32',
    garmentFabric: 'Denim',
    ean: '6112233445566',
    mrp: 1999,
    stock: 8,
    styleNo: 'DNM-101',
    toonLabel: 'TN-JEANS-BLU',
    productName: 'Men Stretchable Slim Jeans',
    rawRow: {},
  },
  {
    storeName: 'Salem Outlet',
    productGroup: 'MEN',
    department: 'Bottom Wear',
    classBrand: 'Denim Co',
    colour: 'Dark Blue',
    size: '32',
    garmentFabric: 'Denim',
    ean: '6112233445566',
    mrp: 1999,
    stock: 5,
    styleNo: 'DNM-101',
    toonLabel: 'TN-JEANS-BLU',
    productName: 'Men Stretchable Slim Jeans',
    rawRow: {},
  },
  {
    storeName: 'Karur Main',
    productGroup: 'MEN',
    department: 'Inner Wear',
    classBrand: 'GM Comfort',
    colour: 'White',
    size: 'L',
    garmentFabric: 'Combed Cotton',
    ean: '6223344556677',
    mrp: 299,
    stock: 50,
    styleNo: 'VST-05',
    toonLabel: 'TN-VEST-WHT',
    productName: 'Men Sleeveless Gym Vest',
    rawRow: {},
  },
  {
    storeName: 'Karur Main',
    productGroup: 'WOMEN',
    department: 'Top Wear',
    classBrand: 'Style Queen',
    colour: 'Maroon',
    size: 'S',
    garmentFabric: 'Rayon',
    ean: '8901234567890',
    mrp: 1499,
    stock: 12,
    styleNo: 'WQ-201',
    toonLabel: 'TN-TUNIC-MRN',
    productName: 'Women Printed Floral Tunic Top',
    rawRow: {},
  },
  {
    storeName: 'Erode Branch',
    productGroup: 'WOMEN',
    department: 'Top Wear',
    classBrand: 'Style Queen',
    colour: 'Maroon',
    size: 'S',
    garmentFabric: 'Rayon',
    ean: '8901234567890',
    mrp: 1499,
    stock: 9,
    styleNo: 'WQ-201',
    toonLabel: 'TN-TUNIC-MRN',
    productName: 'Women Printed Floral Tunic Top',
    rawRow: {},
  },
  {
    storeName: 'Karur Main',
    productGroup: 'WOMEN',
    department: 'Ethnic Wear',
    classBrand: 'Anarkali House',
    colour: 'Yellow',
    size: 'M',
    garmentFabric: 'Silk Blend',
    ean: '8909876543210',
    mrp: 2499,
    stock: 5,
    styleNo: 'KUR-302',
    toonLabel: 'TN-KURTI-YLW',
    productName: 'Women Embroidered Straight Kurti',
    rawRow: {},
  },
  {
    storeName: 'Chennai Express',
    productGroup: 'WOMEN',
    department: 'Ethnic Wear',
    classBrand: 'Anarkali House',
    colour: 'Yellow',
    size: 'M',
    garmentFabric: 'Silk Blend',
    ean: '8909876543210',
    mrp: 2499,
    stock: 7,
    styleNo: 'KUR-302',
    toonLabel: 'TN-KURTI-YLW',
    productName: 'Women Embroidered Straight Kurti',
    rawRow: {},
  },
  {
    storeName: 'Karur Main',
    productGroup: 'KIDS',
    department: 'Boys Top Wear',
    classBrand: 'Junior Star',
    colour: 'Red',
    size: '28',
    garmentFabric: 'Cotton',
    ean: '6334455667788',
    mrp: 599,
    stock: 18,
    styleNo: 'KDT-01',
    toonLabel: 'TN-BOY-TEE-RED',
    productName: 'Boys Graphic Printed T-Shirt',
    rawRow: {},
  },
  {
    storeName: 'Madurai Hub',
    productGroup: 'KIDS',
    department: 'Boys Top Wear',
    classBrand: 'Junior Star',
    colour: 'Red',
    size: '28',
    garmentFabric: 'Cotton',
    ean: '6334455667788',
    mrp: 599,
    stock: 11,
    styleNo: 'KDT-01',
    toonLabel: 'TN-BOY-TEE-RED',
    productName: 'Boys Graphic Printed T-Shirt',
    rawRow: {},
  },
];
